spring:
  application:
    name: Home
  datasource:
    username: ivan
    password: 1234
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
  flyway:
    locations:
      - classpath:/db/migration
      - classpath:/db/callback