spring:
  application:
    name: Home
  datasource:
    username: postgres
    password: 25d45DbD3f5CA3b3F-gD6E*CaaEgBbb*
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://viaduct.proxy.rlwy.net:11498/railway
  flyway:
    locations:
      - classpath:/db/migration
      - classpath:/db/callback

home:
  jwt:
    secret: bringmetoussr
    expiration-ms: 60000