spring:
  application:
    name: Home
  datasource:
    username: ivan
    password: 1234
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
  mail:
    host: smtp.gmail.com
    port: 587
    username: ivan.duvanov.3@gmail.com
    password: pilnamucvqamgbnz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  flyway:
    locations:
      - classpath:/db/migration
      - classpath:/db/callback