spring:
  application:
    name: Home
  datasource:
    username: ivan
    password: 1234
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
  flyway:
    locations:
      - classpath:/db/migration
      - classpath:/db/callback
  mail:
    host: smtp.gmail.com
    port: 587
    username: ivan.duvanov.3@gmail.com
    password: pilnamucvqamgbnz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

home:
  jwt:
    secret: nevergonnagiveyouupnevergonnaletyoudownnevergonnarunaroundanddesertyou
    expiration-ms: 1440000
    refresh-expiration: 10080000
server:
  port: 8080

  #piln amuc vqam gbnz